name: "Setup Python + deps"
description: "Composite action to setup Python and install requirements from a requirements file."
inputs:
  python-version:
    description: 'Python version to install (e.g. 3.11)'
    required: false
    default: '3.11'
  requirements-file:
    description: 'Path to the requirements file to install (relative to repo root)'
    required: false
    default: 'requirements.txt'
runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r ${{ inputs.requirements-file }}
