name: Bittrex
on:
  schedule:
    - cron:  '3 0 * * *'

jobs:
  build:
    name: Bittrex tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v2

      - run: python3 bittrex/pairs.py -q BTC > bittrex/bittrex_BTC_pairs.txt
      - run: python3 bittrex/pairs.py -q USD > bittrex/bittrex_USD_pairs.txt
      - run: python3 bittrex/pairs.py -q ETH > bittrex/bittrex_ETH_pairs.txt
      - run: python3 bittrex/pairs.py > bittrex/bittrex_all_pairs.txt
      - run: python3 bittrex/pairs.py -s > bittrex/bittrex_stocks.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bittrex/
          git diff-index --quiet HEAD || git commit -m "Bittrex: automatic update" -a
          git pull --rebase && git push