name: Bybit
on:
  schedule:
    - cron:  '9 0 * * *'

jobs:
  build:
    name: Bybit tickers
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v4

      - run: python3 bybit/pairs.py > bybit/bybit_futures.txt
      - run: python3 bybit/pairs.py -q USD > bybit/bybit_USD_futures.txt
      - run: python3 bybit/pairs.py -q USDT > bybit/bybit_USDT_futures.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bybit/
          git diff-index --quiet HEAD || git commit -m "Bybit: automatic update" -a
          git pull --rebase && git push
