name: Stocks
on:
  schedule:
    - cron:  '8 0 * * *'

jobs:
  build:
    name: Nasdaqtrader
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - uses: actions/checkout@v5

      - run: python3 stocks/nasdaqtrader.py -nyse | sort > stocks/NYSE_pairs.txt
      - run: python3 stocks/nasdaqtrader.py --nasdaq | sort > stocks/NASDAQ_pairs.txt
      - run: python3 stocks/nasdaqtrader.py -arca | sort > stocks/ARCA_pairs.txt

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add stocks/
          git diff-index --quiet HEAD || git commit -m "NasdaqTrader: automatic update" -a
          git pull --rebase && git push